version: '3.9'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 't1_openschool_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '12345'
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql